name: Github Test Curl

on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X GET https://miranda-express.azurewebsites.net/
